import Head from 'next/head'
import Image from 'next/image'

import Viewer from '../components/Viewer';

import styles from '../styles/Home.module.css'

const PDF = 'https://colbyfayockcom.wpengine.com/wp-content/uploads/2022/02/TalksSiege-Media-Next.js.pdf';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Viewer src={PDF} width="1500" height="844" />
      </main>
    </div>
  )
}
